config/routes.rb
Rails.application.routes.draw do
  root 'used_urls#new'
  get '/used_urls', to: 'used_urls#index'
  get '/:short_name', to: 'used_urls#show'
  get '/used_urls/:short_name/edit', to: 'used_urls#edit'
  delete '/used_urls/:short_name', to: 'used_urls#destroy'
  patch '/used_urls/:short_name', to: 'used_urls#update'
  resources :used_urls
  resources :available_urls
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/available_url.rb
class AvailableUrl < ApplicationRecord
    self.primary_key = :name
    has_one :used_url, :foreign_key => :short_name, :primary_key => :name
end

app/models/used_url.rb
class UsedUrl < ApplicationRecord
    self.primary_key = :short_name
    has_one :available_url, :foreign_key => :name, :primary_key => :short_name
    validates :long_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/available_urls_controller.rb
class AvailableUrlsController < ApplicationController
  before_action :set_available_url, only: %i[ show edit update destroy ]

  # GET /available_urls or /available_urls.json
  def index
    @available_urls = AvailableUrl.all
  end

  # GET /available_urls/1 or /available_urls/1.json
  def show
  end

  # GET /available_urls/new
  def new
    @available_url = AvailableUrl.new
  end

  # GET /available_urls/1/edit
  def edit
  end

  # POST /available_urls or /available_urls.json
  def create
    @available_url = AvailableUrl.new(available_url_params)

    respond_to do |format|
      if @available_url.save
        format.html { redirect_to @available_url, notice: "Available url was successfully created." }
        format.json { render :show, status: :created, location: @available_url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @available_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /available_urls/1 or /available_urls/1.json
  def update
    respond_to do |format|
      if @available_url.update(available_url_params)
        format.html { redirect_to @available_url, notice: "Available url was successfully updated." }
        format.json { render :show, status: :ok, location: @available_url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @available_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /available_urls/1 or /available_urls/1.json
  def destroy
    debugger
    @available_url.destroy
    respond_to do |format|
      format.html { redirect_to available_urls_url, notice: "Available url was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_available_url
      @available_url = AvailableUrl.find_by(name: params[:name])
    end

    # Only allow a list of trusted parameters through.
    def available_url_params
      params.require(:available_url).permit(:name)
    end
end

app/controllers/used_urls_controller.rb
class UsedUrlsController < ApplicationController
  before_action :set_used_url, only: %i[ show edit update destroy ]

  # GET /used_urls or /used_urls.json
  def index
    @used_urls = UsedUrl.all
  end

  # GET /used_urls/1 or /used_urls/1.json
  def show
    # perhaps check if we should get a valid return from the long name first 
    # Actually, maybe not, it really isnt our responsibility
    if @used_url
      redirect_to @used_url.long_name
    else
      format.html { redirect_to edit_used_url_path(@used_url.short_name), notice: "Unable to Link to the TinyUrl." }
      format.json { render :show, status: :created, location: edit_used_url_path(@used_url.short_name) }
    end
  end

  # GET /used_urls/new
  def new
    @used_url = UsedUrl.new
  end

  # GET /used_urls/1/edit
  def edit
  end

  # POST /used_urls or /used_urls.json
  def create
    # How terrible this is right now retrieving AvailableUrl.all 
    @used_url = UsedUrl.new(used_url_params)
    @used_url.short_name = AvailableUrl.all.first.name
    @used_url.available_url.delete
    @used_url.last_used = Time.now

    respond_to do |format|
      if @used_url.save
        format.html { redirect_to edit_used_url_path(@used_url.short_name), 
              notice: "A TinyURL was successfully created." }
        format.json { render :show, status: :created, 
              location: edit_used_url_path(@used_url.short_name) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @used_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /used_urls/1 or /used_urls/1.json
  def update
    @used_url.last_used = Time.now
    respond_to do |format|
      if @used_url.update(used_url_params)
        format.html { redirect_to edit_used_url_path(@used_url.short_name), notice: "TinyURL was successfully updated." }
        format.json { render :show, status: :ok, location: edit_used_url_path(@used_url.short_name) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @used_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /used_urls/1 or /used_urls/1.json
  def destroy
    @used_url.destroy
    respond_to do |format|
      format.html { redirect_to used_urls_url, notice: "TinyURL was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_used_url
      @used_url = UsedUrl.find_by(short_name: params[:short_name])
    end

    # Only allow a list of trusted parameters through.
    def used_url_params
      params.require(:used_url).permit(:long_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/available_urls_helper.rb
module AvailableUrlsHelper
end

app/helpers/used_urls_helper.rb
module UsedUrlsHelper
end

app/views/available_urls/_form.html.erb
<%= form_with(model: available_url) do |form| %>
  <% if available_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(available_url.errors.count, "error") %> prohibited this available_url from being saved:</h2>

      <ul>
        <% available_url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/available_urls/edit.html.erb
<h1>Editing Available Url</h1>

<%= render 'form', available_url: @available_url %>

<%= link_to 'Show', @available_url %> |
<%= link_to 'Back', available_urls_path %>

app/views/available_urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Available Urls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @available_urls.each do |available_url| %>
      <tr>
        <td><%= available_url.name %></td>
        <td><%= link_to 'Show', available_url %></td>
        <td><%= link_to 'Edit', edit_available_url_path(available_url) %></td>
        <td><%= link_to 'Destroy', available_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Available Url', new_available_url_path %>

app/views/available_urls/new.html.erb
<h1>Available Urls</h1>

<%= render 'form', available_url: @available_url %>

<%= link_to 'Back', available_urls_path %>

app/views/available_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @available_url.name %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinyurl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #FF8000">
    <div class="page">
      <div class="main border border-primary rounded">
        <div id="tab">
          <p><%= image_tag("tinyurl-rails.jpg") %></p>
          <%= yield %>
        </div>
        <div class="border border-primary rounded-bottom foot">
        <br>
        <p>© 2021 Copyright: Robert S. Young</p>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/used_urls/_form.html.erb
<script>
function clear_long_name() {
    document.getElementById("used_url_long_name").value = '';
}
</script>

<%= form_with(model: used_url) do |form| %>
  <% if used_url.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(used_url.errors.count, "error") %> prohibited this used_url from being saved:</p>

      <ul>
        <% used_url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>The following is your TinyURL...</p>
  <h2>
  <a href="<%= root_url + @used_url.short_name %>" target="_blank">
  <%= root_url + @used_url.short_name %></a>
  </h2>

  <div class="field">
    <p>Unused links that have not been used in 30 days are recycled!</p>
    <p>FYI this TinyURL and link was last used or modified 
    <%= time_ago_in_words @used_url.last_used %> ago.</p>
  </div>

  <div class="field">
    <p>Feel free to modify the associated link. Currently it is...</p>
    <%= form.text_area :long_name, :cols => 30, :rows => 5 %>
  </div>

  <div class="actions">
  <button type="button" class="btn btn-primary" onclick="clear_long_name();">Clear</button>
    <%= form.submit "Save the Link", method: :post, class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/used_urls/_new_form.html.erb
<%= form_with(model: used_url) do |form| %>
  <% if used_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(used_url.errors.count, "error") %> prohibited this used_url from being saved:</h2>

      <ul>
        <% used_url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :long_name, :cols => 30, :rows => 5 %>
  </div>

  <div class="actions">
    <%= form.submit "Create TinyUrl", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/used_urls/edit.html.erb
<p id="notice"><%= notice %></p>
<%= render 'form', used_url: @used_url %>
<br>
<%= link_to 'Create a new TinyURL', root_path %> | 
<%= link_to 'See all your TinyURLs', used_urls_url %>

app/views/used_urls/index.html.erb
<p id="notice"><%= notice %></p>
<div class="highlight">
<p>You currently have <%= pluralize(@used_urls.length, "TinyURL") %></p>
</div>
<div>
  <% @used_urls.each.with_index do |used_url, i| %>
      <% if i % 2 == 0 %>
        <div class = "clear">
      <% else %>
        <div class = "highlight">
      <% end %>
        <p>Created <%= time_ago_in_words used_url.created_at %> ago, and 
        last used or updated <%= time_ago_in_words used_url.last_used %> ago.
        </p>
        <p>The TinyURL is <a href="http://localhost:3000/<%= used_url.short_name %>" target="_blank">
        http://localhost:3000/<%= used_url.short_name %></a></p>
        <p>The associated link is...</p>
        <div width="25">
        <p><a href="<%= used_url.long_name %>" target="_blank"><%= used_url.long_name %></a>
        </p>
        </div>
        <p>Feel free to <%= link_to 'Update this TinyURL', edit_used_url_path(used_url.short_name) %>
         or <%= link_to 'Delete this TinyURL', used_url, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
        </div>
      </td>
    </tr>
  <% end %>
</div>

<br>

<%= link_to 'Create a new TinyURL', root_path %>

app/views/used_urls/new.html.erb
<p>Enter the link below to create a new TinyURL...</p>

<%= render 'new_form', used_url: @used_url %>
<br>
<p>Or see all previously created <%= link_to "TinyURLs", used_urls_url %></p>

app/views/used_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>TinyUrl:</strong>
  http://localhost:3000/<%= @used_url.short_name %>
</p>

<p>
  <strong>Long name:</strong>
  <%= @used_url.long_name %>
</p>

<p>
  <strong>Created Date:</strong>
  <%= @used_url.created_at %>
</p>

<p>
  <strong>Last Used Date:</strong>
  <%= @used_url.last_used %>
</p>

<%= link_to 'Edit', edit_used_url_path(@used_url) %> |
<%= link_to 'Back', used_urls_path %>